AWSTemplateFormatVersion: "2010-09-09"
Description: Pipeline for building the event-source-blog example
Parameters:
  GithubAccessToken:
    Type: String
    NoEcho: true
    Description: OAuth Token for the github repository
Resources:
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codebuild.amazonaws.com"
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "codepipeline.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
  ArtifactStorage:
    Type: "AWS::S3::Bucket"